name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
permissions:
  contents: write
env:
  PROTOC_VERSION: "32.0"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            runtime: windows-x64
          - target: aarch64-pc-windows-msvc
            runtime: windows-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: v${{ inputs.version }}
      - name: cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}
      - name: cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: install protoc
        run: |
          $PROTOC_ZIP = "protoc-${{ env.PROTOC_VERSION }}-win64.zip"
          Invoke-WebRequest -Uri "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP" -OutFile $PROTOC_ZIP
          Expand-Archive -Path $PROTOC_ZIP -DestinationPath "$HOME\.protoc"
      - name: update path
        run: Add-Content $env:GITHUB_PATH "$HOME\.protoc\bin"
      - name: build rust .dll
        run: cargo build --release --target ${{ matrix.target }}
      - name: upload .dll
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runtime }}
          path: .\target\${{ matrix.target }}\release\tokenizers_proto.dll

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runtime: linux-x64
            flags: RUSTFLAGS="-C linker=/usr/bin/clang"
          - target: aarch64-unknown-linux-gnu
            runtime: linux-arm64
            flags: RUSTFLAGS="-C linker=/usr/bin/clang -C link-arg=--target=aarch64-linux-gnu -C link-arg=--gcc-toolchain=/usr"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      - name: cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}
      - name: cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}
      - name: install packages
        run: |
          sudo apt update
          sudo apt install -y clang unzip gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: install protoc
        run: |
          PROTOC_ZIP="protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip"
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP"
          unzip $PROTOC_ZIP -d $HOME/.protoc
      - name: update path
        run: echo "$HOME/.protoc/bin" >> $GITHUB_PATH
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: build rust .so
        run: ${{ matrix.flags }} cargo build --release --target ${{ matrix.target }}
      - name: upload .so
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runtime }}
          path: target/${{ matrix.target }}/release/libtokenizers_proto.so

  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            runtime: darwin-x64
          - target: aarch64-apple-darwin
            runtime: darwin-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      - name: cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-${{ matrix.runtime }}
      - name: cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-target-${{ matrix.runtime }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: install protoc
        run: |
          PROTOC_ZIP="protoc-${{ env.PROTOC_VERSION }}-osx-aarch_64.zip"
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP"
          unzip $PROTOC_ZIP -d $HOME/.protoc
      - name: update path
        run: echo "$HOME/.protoc/bin" >> $GITHUB_PATH
      - name: build rust .dylib
        run: cargo build --release --target ${{ matrix.target }}
      - name: upload .dylib
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runtime }}
          path: target/${{ matrix.target }}/release/libtokenizers_proto.dylib

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-windows
      - build-linux
      - build-darwin
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      - uses: actions/download-artifact@v4
        with:
          path: binaries
      - run: sudo apt install -y zip
      - run: for dir in binaries/*/; do dir=${dir%/};zip -rj "${dir}.zip" "$dir"; done
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          draft: false
          files: |
            binaries/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
